<?php
require_once 'config.php'; require_login(); $pdo=db();
$allowed=['datang','pindah','meninggal','lahir']; $jenis=$_GET['jenis']??'datang'; if(!in_array($jenis,$allowed,true))$jenis='datang';
$config=[
'datang'=>['title'=>'Penduduk Datang','table'=>'penduduk_datang','fields'=>['nik'=>'NIK','nama_lengkap'=>'Nama Lengkap','asal'=>'Asal Daerah','tanggal'=>'Tanggal Datang','keterangan'=>'Keterangan']],
'pindah'=>['title'=>'Penduduk Pindah','table'=>'penduduk_pindah','fields'=>['nik'=>'NIK','nama_lengkap'=>'Nama Lengkap','tujuan'=>'Tujuan Daerah','tanggal'=>'Tanggal Pindah','keterangan'=>'Keterangan']],
'meninggal'=>['title'=>'Penduduk Meninggal','table'=>'penduduk_meninggal','fields'=>['nik'=>'NIK','nama_lengkap'=>'Nama Lengkap','tanggal'=>'Tanggal Meninggal','sebab'=>'Sebab/Keterangan']],
'lahir'=>['title'=>'Penduduk Baru Lahir','table'=>'penduduk_lahir','fields'=>['nik'=>'NIK (jika sudah ada)','nama_lengkap'=>'Nama Lengkap','nama_ayah'=>'Nama Ayah','nama_ibu'=>'Nama Ibu','tanggal'=>'Tanggal Lahir','keterangan'=>'Keterangan']]
][$jenis];
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$action=$_POST['action']??'';$table=$config['table'];if($action==='delete'){$pdo->prepare("DELETE FROM `$table` WHERE id=?")->execute([(int)$_POST['id']]);}else{$cols=array_keys($config['fields']);$vals=[];foreach($cols as $c)$vals[]=trim($_POST[$c]??'');if($action==='add'){$pdo->prepare("INSERT INTO `$table` (`".implode('`,`',$cols)."`) VALUES (".implode(',',array_fill(0,count($cols),'?')).")")->execute($vals);} }header('Location: mutasi.php?jenis='.$jenis);exit;}
$rows=$pdo->query("SELECT * FROM `{$config['table']}` ORDER BY id DESC")->fetchAll();
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=$config['title']?></title><link rel="stylesheet" href="assets/style.css"></head><body><div class="app"><aside class="sidebar"><div class="brand"><div class="logo">DC</div><div><b>Desa Cibodas</b><small>Sistem Kependudukan</small></div></div><nav><a href="index.php">Dashboard</a><a href="penduduk.php">Data Penduduk</a><a class="<?=($jenis==='datang'?'active':'')?>" href="?jenis=datang">Penduduk Datang</a><a class="<?=($jenis==='pindah'?'active':'')?>" href="?jenis=pindah">Penduduk Pindah</a><a class="<?=($jenis==='meninggal'?'active':'')?>" href="?jenis=meninggal">Penduduk Meninggal</a><a class="<?=($jenis==='lahir'?'active':'')?>" href="?jenis=lahir">Penduduk Baru Lahir</a></nav><a class="logout" href="logout.php">Keluar</a></aside><main class="main"><header class="topbar"><div><h1><?=$config['title']?></h1><p>Kelola data mutasi kependudukan.</p></div></header>
<section class="panel"><h2>Tambah Data</h2><form class="grid-form" method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="add"><?php foreach($config['fields'] as $name=>$label): ?><label><?=$label?><input name="<?=$name?>" <?=$name==='tanggal'?'type="date"':''?> required></label><?php endforeach; ?><div class="form-actions"><button>Simpan</button></div></form></section>
<section class="panel"><h2>Daftar Data (<?=count($rows)?>)</h2><div class="table-wrap"><table><thead><tr><th>No</th><?php foreach($config['fields'] as $label): ?><th><?=$label?></th><?php endforeach; ?><th>Aksi</th></tr></thead><tbody><?php foreach($rows as $i=>$r): ?><tr><td><?=$i+1?></td><?php foreach(array_keys($config['fields']) as $c): ?><td><?=e((string)$r[$c])?></td><?php endforeach; ?><td><form method="post" onsubmit="return confirm('Hapus data ini?')"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="link-danger">Hapus</button></form></td></tr><?php endforeach; ?></tbody></table></div></section></main></div></body></html>
